package aidp;

import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.util.concurrent.CompletableFuture;

public class RequestHandler {
	private static String apiKey = "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";
  	private static String apiUrl = "https://api.openai.com/v1/chat/completions";
    private static String model = "gpt-3.5-turbo";
    private static HttpClient httpClient = HttpClient.newHttpClient();

	private static int statusCode = 0;	
	private static String responseBody = "";

	public static Request makeRequest(String system, String user, double temperature) {
		String messagesArray = "[";
		if (system != "") messagesArray += String.format("{\"role\": \"system\", \"content\": \"%s\"}", system);
		if (user != "") messagesArray += String.format(",{\"role\": \"user\", \"content\": \"%s\"}", user); 
		messagesArray += "]";
			
  		String requestBody = String.format("{\"model\": \"%s\", \"messages\": %s, \"temperature\": %f}",
			model, messagesArray, temperature);
		
  		HttpRequest httpRequest = HttpRequest.newBuilder()
		   .uri(URI.create(apiUrl))
		   .POST(HttpRequest.BodyPublishers.ofString(requestBody))
		   .header("Content-Type", "application/json")
		   .header("Authorization", "Bearer " + apiKey)
		   .build();
    
	    CompletableFuture<HttpResponse<String>> responseFuture = httpClient.sendAsync(
	        httpRequest, 
	        HttpResponse.BodyHandlers.ofString()
	    );
	
	    responseFuture.thenAccept(response -> {
	        statusCode = response.statusCode();
	        responseBody = response.body();
	    }).join();

		return new Request(requestBody, responseBody, statusCode);
	}
}

/*
* System Messages: These messages provide high-level instructions to guide the model's behavior 
* throughout the conversation. System messages are often used to set the context or tone for the conversation.
* 
* User Messages: User messages are the primary input from the user or developer. These messages 
* can be used to ask questions, provide information, or give instructions. 
* 
* Assistant Messages: Assistant messages are responses generated by the model. They are used to 
* retrieve the model's responses to user queries or to continue the conversation. For
* 
* Temperature Setting: The OpenAI API allows you to adjust the "temperature" parameter when making 
* API calls. A higher temperature (e.g., 0.8) makes the output more random, leading to a wider 
* variety of responses, while a lower temperature (e.g., 0.2) makes the output more deterministic and focused.
*/